# Extra autostart processes
# exec-once = uwsm-app -- my-service

# Automatically disable the laptop display when an external monitor is connected.
exec-once = ~/.config/hypr/scripts/auto-monitor-switch --watch

# exec-once = fcitx5
