onboarding = false

[theme]
name = "terminal"

[keys]
prefix = "ctrl+s"
split_horizontal = "prefix+minus"
split_vertical = "prefix+|"
previous_tab = "ctrl+h"
next_tab = "ctrl+l"
previous_workspace = "prefix+L"
swap_pane_right = ""
cycle_pane_next = "prefix+tab"
focus_pane_down = ""
focus_pane_right = ""
copy_mode = "prefix+["
rename_tab = "prefix+,"
goto = "prefix+j"

[[keys.command]]
key = "prefix+g"
type = "pane"
command = "lazygit"

[ui]
show_agent_labels_on_pane_borders = true

[ui.sound]
enabled = false

[ui.toast]
delivery = "off"

[experimental]
kitty_graphics = true
